displayName=Inventory Banked Counter
author=theovit
description=Shows how many of each inventory item you have in your bank
tags=inventory,bank,count
version=
plugins=com.theovit.BankedCountPlugin
build=standard